services:
  #Servicio de la BD
  db:
    image: mysql:8.0
    container_name: mysql-db-tfg
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --bind-address=0.0.0.0
    environment:
      MYSQL_DATABASE: ${NAME_DB}
      MYSQL_ROOT_PASSWORD: ${PASSWORD_DB}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-p${PASSWORD_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s

  #Servicio de la fastapi
  backend:
    build: ./backend
    container_name: fastapi-backend
    restart: on-failure
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${URL_DB}
      OLLAMA_URL: ${OLLAMA_URL}
      OLLAMA_MODEL: ${OLLAMA_MODEL}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./backend:/code
      - ./.env:/code/.env
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql_data: